# Reservation status
DRAFT = "DRAFT"
PENDING_TEACHER = "PENDING_TEACHER"
PENDING_DIRECTOR = "PENDING_DIRECTOR"
APPROVED = "APPROVED"
REJECTED = "REJECTED"
CANCELLED = "CANCELLED"
COMPLETED = "COMPLETED"
ARCHIVED = "ARCHIVED"

RESERVATION_ACTIVE_STATUSES = (PENDING_TEACHER, PENDING_DIRECTOR, APPROVED)

# Resource status
AVAILABLE = "AVAILABLE"
RESERVED = "RESERVED"
IN_USE = "IN_USE"
MAINTENANCE = "MAINTENANCE"
FAULT = "FAULT"
DISABLED = "DISABLED"

RESOURCE_UNAVAILABLE = (MAINTENANCE, FAULT, DISABLED)

# Task status
PENDING_PREPARE = "PENDING_PREPARE"
READY = "READY"
RUNNING = "RUNNING"
TASK_COMPLETED = "COMPLETED"
TASK_ARCHIVED = "ARCHIVED"
TASK_CANCELLED = "CANCELLED"

# Approval
TEACHER_REVIEW = "TEACHER_REVIEW"
DIRECTOR_APPROVAL = "DIRECTOR_APPROVAL"
APPROVAL_APPROVED = "APPROVED"
APPROVAL_REJECTED = "REJECTED"

# Alarm types
ALARM_NEAR_BOUNDARY = "NEAR_BOUNDARY"
ALARM_OUT_OF_BOUNDARY = "OUT_OF_BOUNDARY"
ALARM_LOW_BATTERY = "LOW_BATTERY"
ALARM_SPEED_LIMIT = "SPEED_LIMIT"
ALARM_DATA_SPIKE = "DATA_SPIKE"

# Pool bounds (meters) for simulation
POOL_WIDTH = 40.0
POOL_HEIGHT = 20.0
BOUNDARY_MARGIN = 2.0
SPEED_LIMIT = 3.0
LOW_BATTERY_THRESHOLD = 20.0
