# Reservation status
DRAFT = "DRAFT"
PENDING_TEACHER = "PENDING_TEACHER"
PENDING_DIRECTOR = "PENDING_DIRECTOR"
APPROVED = "APPROVED"
REJECTED = "REJECTED"
CANCELLED = "CANCELLED"
COMPLETED = "COMPLETED"
ARCHIVED = "ARCHIVED"

RESERVATION_ACTIVE_STATUSES = (PENDING_TEACHER, PENDING_DIRECTOR, APPROVED)

# Resource status
AVAILABLE = "AVAILABLE"
RESERVED = "RESERVED"
IN_USE = "IN_USE"
MAINTENANCE = "MAINTENANCE"
FAULT = "FAULT"
DISABLED = "DISABLED"

RESOURCE_UNAVAILABLE = (MAINTENANCE, FAULT, DISABLED)

# Task status
PENDING_PREPARE = "PENDING_PREPARE"
READY = "READY"
RUNNING = "RUNNING"
TASK_COMPLETED = "COMPLETED"
TASK_ARCHIVED = "ARCHIVED"
TASK_CANCELLED = "CANCELLED"

# Approval
TEACHER_REVIEW = "TEACHER_REVIEW"
DIRECTOR_APPROVAL = "DIRECTOR_APPROVAL"
APPROVAL_APPROVED = "APPROVED"
APPROVAL_REJECTED = "REJECTED"
