-- 达梦 DM8 删表脚本（按外键依赖从子表到父表）
-- 重新执行 init_db.sql 前先运行本脚本，避免「对象已存在」错误。
-- 在达梦管理工具中选中与 init_db.sql 相同的目标模式/用户后执行。

DROP TABLE IF EXISTS DEVICE_COMMAND_LOG CASCADE;
DROP TABLE IF EXISTS VIDEO_RECORD CASCADE;
DROP TABLE IF EXISTS AI_REPORT CASCADE;
DROP TABLE IF EXISTS EXPERIMENT_FILE CASCADE;
DROP TABLE IF EXISTS ALARM_RECORD CASCADE;
DROP TABLE IF EXISTS SHIP_TRACK CASCADE;
DROP TABLE IF EXISTS SENSOR_DATA CASCADE;
DROP TABLE IF EXISTS AI_CALL_LOG CASCADE;
DROP TABLE IF EXISTS EXPERIMENT_TASK CASCADE;
DROP TABLE IF EXISTS EXP_APPROVAL_LOG CASCADE;
DROP TABLE IF EXISTS EXP_RESERVATION_RESOURCE CASCADE;
DROP TABLE IF EXISTS EXP_RESERVATION CASCADE;
DROP TABLE IF EXISTS LAB_RESOURCE CASCADE;
DROP TABLE IF EXISTS SYS_USER_ROLE CASCADE;
DROP TABLE IF EXISTS SYS_OPERATION_LOG CASCADE;
DROP TABLE IF EXISTS SYS_USER CASCADE;
DROP TABLE IF EXISTS SYS_ROLE CASCADE;
