-- 达梦 DM8 建表脚本（课程设计 v2 — 含外键约束与自增主键）
-- 执行前请先创建模式/用户，并在达梦管理工具中选中目标库执行。
-- 本地 SQLite 开发可使用 ORM 自动建表 + python -m scripts.seed_db

-- ========== 用户与角色 ==========
CREATE TABLE SYS_USER (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    USERNAME        VARCHAR(50)     NOT NULL,
    PASSWORD_HASH   VARCHAR(200)    NOT NULL,
    REAL_NAME       VARCHAR(100)    NOT NULL,
    PHONE           VARCHAR(30),
    EMAIL           VARCHAR(100),
    STATUS          VARCHAR(20)     DEFAULT 'ACTIVE' NOT NULL,
    CREATE_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED      INT             DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX UK_SYS_USER_USERNAME ON SYS_USER(USERNAME);

CREATE TABLE SYS_ROLE (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ROLE_CODE       VARCHAR(50)     NOT NULL,
    ROLE_NAME       VARCHAR(100)    NOT NULL,
    CREATE_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX UK_SYS_ROLE_CODE ON SYS_ROLE(ROLE_CODE);

CREATE TABLE SYS_USER_ROLE (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    USER_ID         BIGINT          NOT NULL,
    ROLE_ID         BIGINT          NOT NULL,
    CONSTRAINT FK_SUR_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER(ID),
    CONSTRAINT FK_SUR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE(ID)
);
CREATE INDEX IDX_USER_ROLE_USER ON SYS_USER_ROLE(USER_ID);
CREATE INDEX IDX_USER_ROLE_ROLE ON SYS_USER_ROLE(ROLE_ID);

-- ========== 资源设备 ==========
CREATE TABLE LAB_RESOURCE (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    RESOURCE_CODE   VARCHAR(50)     NOT NULL,
    RESOURCE_NAME   VARCHAR(100)    NOT NULL,
    RESOURCE_TYPE   VARCHAR(50)     NOT NULL,
    STATUS          VARCHAR(20)     DEFAULT 'AVAILABLE' NOT NULL,
    LOCATION        VARCHAR(200),
    MANAGER_ID      BIGINT,
    DESCRIPTION     VARCHAR(500),
    CREATE_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED      INT             DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX UK_LAB_RESOURCE_CODE ON LAB_RESOURCE(RESOURCE_CODE);
CREATE INDEX IDX_LAB_RESOURCE_STATUS ON LAB_RESOURCE(STATUS);

-- ========== 预约主从表 ==========
CREATE TABLE EXP_RESERVATION (
    ID                      BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    RESERVATION_NO          VARCHAR(50)     NOT NULL,
    EXP_NAME                VARCHAR(100)    NOT NULL,
    EXP_TYPE                VARCHAR(50),
    APPLICANT_ID            BIGINT          NOT NULL,
    TEACHER_ID              BIGINT,
    START_TIME              TIMESTAMP       NOT NULL,
    END_TIME                TIMESTAMP       NOT NULL,
    STATUS                  VARCHAR(30)     DEFAULT 'DRAFT' NOT NULL,
    PURPOSE                 CLOB,
    PLAN_SUMMARY            CLOB,
    SUBMIT_TIME             TIMESTAMP,
    TEACHER_REVIEW_BY       BIGINT,
    TEACHER_REVIEW_TIME     TIMESTAMP,
    TEACHER_REVIEW_COMMENT  VARCHAR(500),
    DIRECTOR_APPROVED_BY    BIGINT,
    DIRECTOR_APPROVED_TIME  TIMESTAMP,
    DIRECTOR_APPROVAL_COMMENT VARCHAR(500),
    REJECT_REASON           VARCHAR(500),
    CREATE_TIME             TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME             TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED              INT             DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX UK_EXP_RESERVATION_NO ON EXP_RESERVATION(RESERVATION_NO);
CREATE INDEX IDX_EXP_RES_STATUS ON EXP_RESERVATION(STATUS);
CREATE INDEX IDX_EXP_RES_APPLICANT ON EXP_RESERVATION(APPLICANT_ID);
CREATE INDEX IDX_EXP_RES_START ON EXP_RESERVATION(START_TIME);
CREATE INDEX IDX_EXP_RES_END ON EXP_RESERVATION(END_TIME);

CREATE TABLE EXP_RESERVATION_RESOURCE (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    RESERVATION_ID  BIGINT          NOT NULL,
    RESOURCE_ID     BIGINT          NOT NULL,
    RESOURCE_TYPE   VARCHAR(50),
    QUANTITY        INT             DEFAULT 1,
    START_TIME      TIMESTAMP       NOT NULL,
    END_TIME        TIMESTAMP       NOT NULL,
    REMARK          VARCHAR(500)
);
CREATE INDEX IDX_EXP_RES_RES_RESERVATION ON EXP_RESERVATION_RESOURCE(RESERVATION_ID);
CREATE INDEX IDX_EXP_RES_RES_RESOURCE ON EXP_RESERVATION_RESOURCE(RESOURCE_ID);
CREATE INDEX IDX_EXP_RES_RES_TIME ON EXP_RESERVATION_RESOURCE(START_TIME, END_TIME);

CREATE TABLE EXP_APPROVAL_LOG (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    RESERVATION_ID  BIGINT          NOT NULL,
    STEP_TYPE       VARCHAR(30)     NOT NULL,
    APPROVER_ID     BIGINT          NOT NULL,
    RESULT          VARCHAR(20)     NOT NULL,
    COMMENT         VARCHAR(500),
    ACTION_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_EXP_APPROVAL_RES ON EXP_APPROVAL_LOG(RESERVATION_ID);

-- ========== 试验任务与过程数据 ==========
CREATE TABLE EXPERIMENT_TASK (
    ID                  BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    TASK_NO             VARCHAR(50)     NOT NULL,
    RESERVATION_ID      BIGINT          NOT NULL,
    EXP_NAME            VARCHAR(100)    NOT NULL,
    STATUS              VARCHAR(30)     DEFAULT 'PENDING_PREPARE' NOT NULL,
    ACTUAL_START_TIME   TIMESTAMP,
    ACTUAL_END_TIME     TIMESTAMP,
    OPERATOR_ID         BIGINT,
    ARCHIVE_TIME        TIMESTAMP,
    CREATE_TIME         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED          INT             DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX UK_EXPERIMENT_TASK_NO ON EXPERIMENT_TASK(TASK_NO);
CREATE INDEX IDX_EXPERIMENT_TASK_RES ON EXPERIMENT_TASK(RESERVATION_ID);
CREATE INDEX IDX_EXPERIMENT_TASK_STATUS ON EXPERIMENT_TASK(STATUS);

CREATE TABLE SENSOR_DATA (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    EXPERIMENT_ID   BIGINT          NOT NULL,
    TIMESTAMP       TIMESTAMP       NOT NULL,
    POSITION_X      DECIMAL(10,2),
    POSITION_Y      DECIMAL(10,2),
    SPEED           DECIMAL(10,2),
    HEADING         DECIMAL(10,2),
    ROLL            DECIMAL(10,2),
    PITCH           DECIMAL(10,2),
    BATTERY         DECIMAL(10,2),
    RESISTANCE      DECIMAL(10,2)
);
CREATE INDEX IDX_SENSOR_DATA_EXP ON SENSOR_DATA(EXPERIMENT_ID);
CREATE INDEX IDX_SENSOR_DATA_TS ON SENSOR_DATA(TIMESTAMP);

CREATE TABLE SHIP_TRACK (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    EXPERIMENT_ID   BIGINT          NOT NULL,
    TIMESTAMP       TIMESTAMP       NOT NULL,
    POSITION_X      DECIMAL(10,2),
    POSITION_Y      DECIMAL(10,2),
    HEADING         DECIMAL(10,2)
);
CREATE INDEX IDX_SHIP_TRACK_EXP ON SHIP_TRACK(EXPERIMENT_ID);

CREATE TABLE ALARM_RECORD (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    EXPERIMENT_ID   BIGINT          NOT NULL,
    ALARM_TYPE      VARCHAR(50)     NOT NULL,
    ALARM_LEVEL     VARCHAR(20),
    ALARM_MESSAGE   VARCHAR(500),
    HANDLE_STATUS   VARCHAR(20)     DEFAULT 'PENDING',
    HANDLER_ID      BIGINT,
    HANDLE_TIME     TIMESTAMP,
    HANDLE_COMMENT  VARCHAR(500),
    CREATE_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_ALARM_RECORD_EXP ON ALARM_RECORD(EXPERIMENT_ID);

CREATE TABLE EXPERIMENT_FILE (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    EXPERIMENT_ID   BIGINT          NOT NULL,
    FILE_NAME       VARCHAR(200)    NOT NULL,
    FILE_TYPE       VARCHAR(50),
    FILE_PATH       VARCHAR(500)    NOT NULL,
    UPLOAD_BY       BIGINT,
    UPLOAD_TIME     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED      INT             DEFAULT 0 NOT NULL
);
CREATE INDEX IDX_EXPERIMENT_FILE_EXP ON EXPERIMENT_FILE(EXPERIMENT_ID);

CREATE TABLE AI_REPORT (
    ID              BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
    EXPERIMENT_ID   BIGINT          NOT NULL,
    REPORT_TITLE    VARCHAR(200),
    SUMMARY_TEXT    CLOB,
    ANALYSIS_TEXT   CLOB,
    MODEL_NAME      VARCHAR(100),
    GENERATED_BY    BIGINT,
    GENERATED_TIME  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED      INT             DEFAULT 0 NOT NULL
);
CREATE INDEX IDX_AI_REPORT_EXP ON AI_REPORT(EXPERIMENT_ID);

-- ========== 业务外键约束（主从表与试验数据关联） ==========
ALTER TABLE EXP_RESERVATION_RESOURCE
    ADD CONSTRAINT FK_ERR_RESERVATION
    FOREIGN KEY (RESERVATION_ID) REFERENCES EXP_RESERVATION(ID);

ALTER TABLE EXP_RESERVATION_RESOURCE
    ADD CONSTRAINT FK_ERR_RESOURCE
    FOREIGN KEY (RESOURCE_ID) REFERENCES LAB_RESOURCE(ID);

ALTER TABLE EXP_APPROVAL_LOG
    ADD CONSTRAINT FK_EAL_RESERVATION
    FOREIGN KEY (RESERVATION_ID) REFERENCES EXP_RESERVATION(ID);

ALTER TABLE EXPERIMENT_TASK
    ADD CONSTRAINT FK_ET_RESERVATION
    FOREIGN KEY (RESERVATION_ID) REFERENCES EXP_RESERVATION(ID);

ALTER TABLE SENSOR_DATA
    ADD CONSTRAINT FK_SD_EXPERIMENT
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_TASK(ID);

ALTER TABLE SHIP_TRACK
    ADD CONSTRAINT FK_ST_EXPERIMENT
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_TASK(ID);

ALTER TABLE ALARM_RECORD
    ADD CONSTRAINT FK_AR_EXPERIMENT
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_TASK(ID);

ALTER TABLE EXPERIMENT_FILE
    ADD CONSTRAINT FK_EF_EXPERIMENT
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_TASK(ID);

ALTER TABLE AI_REPORT
    ADD CONSTRAINT FK_AIR_EXPERIMENT
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_TASK(ID);
