-- 达梦 DM8 角色种子数据（用户密码请使用 python -m scripts.seed_db 写入 bcrypt 摘要）
-- 若手工插入用户，PASSWORD_HASH 需为 bcrypt('123456') 的哈希值

INSERT INTO SYS_ROLE (ID, ROLE_CODE, ROLE_NAME) VALUES (1, 'ADMIN', '系统管理员');
INSERT INTO SYS_ROLE (ID, ROLE_CODE, ROLE_NAME) VALUES (2, 'DIRECTOR', '试验场主任');
INSERT INTO SYS_ROLE (ID, ROLE_CODE, ROLE_NAME) VALUES (3, 'TEACHER', '指导教师');
INSERT INTO SYS_ROLE (ID, ROLE_CODE, ROLE_NAME) VALUES (4, 'STUDENT', '学生/研究员');
INSERT INTO SYS_ROLE (ID, ROLE_CODE, ROLE_NAME) VALUES (5, 'MAINTAINER', '设备维护人员');

COMMIT;
